export const CHANGE_SEARCH_FIELD = "HANGE_SEARCH_FIELD"

export const REQUEST_CATNAMES_PENDING = "REQUEST_CATNAMES_PENDING"
export const REQUEST_CATNAMES_SUCCESS = "REQUEST_CATNAMES_SUCCESS"
export const REQUEST_CATNAMES_FAILED = "REQUEST_CATNAMES_FAILED"